version: "3.1"

stories:
- story: greet
  steps:
  - intent: greet
  - action: utter_greet

- story: track order
  steps:
  - intent: track_order
  - action: utter_track_order

- story: refund policy
  steps:
  - intent: refund_policy
  - action: utter_refund_policy

- story: faq
  steps:
  - intent: faq
  - action: utter_faq

- story: talk to human
  steps:
  - intent: talk_to_human
  - action: utter_talk_to_human

- story: goodbye
  steps:
  - intent: goodbye
  - action: utter_goodbye

- story: fallback
  steps:
  - intent: fallback
  - action: utter_fallback
